{
	"version": 1684595558,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/bg-sheet0.png",
		"images/qz-sheet0.png",
		"images/qz-sheet1.png",
		"images/cowboy-sheet0.png",
		"images/cowboy-sheet1.png",
		"images/zombie-sheet0.png",
		"images/bullet-sheet0.png",
		"images/bt_select-sheet0.png",
		"images/total2-sheet0.png",
		"images/logo-sheet0.png",
		"images/play-sheet0.png",
		"images/exit-sheet0.png",
		"images/p1-sheet0.png",
		"images/back-sheet0.png",
		"images/paper-sheet0.png",
		"images/logo2-sheet0.png",
		"images/q-sheet0.png",
		"images/bat-sheet0.png",
		"images/bat-sheet1.png",
		"images/help-sheet0.png",
		"images/bghelp-sheet0.png",
		"images/kersor-sheet0.png",
		"media/es_video game loading - sfx producer (online-audio-converter.com).ogg",
		"media/click-button-140881 (online-audio-converter.com).ogg",
		"media/videogame-death-sound-43894 (online-audio-converter.com).ogg",
		"media/game-over-38511 (online-audio-converter.com).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}